language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master
matrix:
  allow_failures:
    - go: master
go_import_path: go.kelfa.io
before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run --enable gosec
  - go test -v -race ./...
