language: go
go:
  - 1.x
  - "1.10"
  - 1.11.x
  - master
go_import_path: go.kelfa.io/elf
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run --enable gosec
  - go test -v -race ./...
