language: go
go:
  - 1.x
  - "1.10"
  - 1.11.x
  - master
go_import_path: go.kelfa.io/elf
before_script:
  - go install https://github.com/securego/gosec/cmd/gosec
script:
  - go test -v ./...
  - gosec ./...
